Added create_db.py script
capstoneteamb/capstone360 pull request #154
Opened 2019-06-14 20:31 UTC by falikhan

To test:
1- Connect to the VM 
2- Navigate to the capstone360 file
3- Run "python create_db.py"
4- Enter correct username: "c360app"
5- Enter correct password

2019-06-14 20:37 UTC, J8cob1 reviewed
Can we make the prof db script fish credentials out of the app configuration file like the insert professor and remove professor scripts? Also, we take the insert and remove professor link out of this branch? Those are already in another PR.

2019-06-14 22:09 UTC, pdx-cs-lbryan requested changes
I agree with Jacob's comment -- please remove the files from Christian's PR and copy the authentication code from his files

2019-06-15 03:05 UTC, pdx-cs-lbryan requested changes
Dropping tables doesn't seem to be working.

When I run the script on the vm, it reports back with an error saying that the professors table already exists

edit 1: ran this after commenting out the drop code, and it seems to be giving us trouble

edit 2: so the drop code was locking the db or otherwise preventing other processes access to it.

2019-06-15 07:44 UTC, pdx-cs-lbryan approved these changes

2019-06-15 07:44 UTC, merged