Prof dashboard
capstoneteamb/capstone360 pull request #20
Opened 2019-04-20 01:42 UTC by falikhan

Resolved merge conflicts.

2019-04-20 08:12 UTC, pdx-cs-lbryan requested changes
1.  please remove any file that's not in master unless you're adding it for your code (ex: db_form.py, db_test.db)
2. may need to look into licenses for some of the libraries used. We can talk to the group about this.
3. please leave the run command in app.py as it is in master
4. Should selecting a term currently display only the students/teams in that term? Right now it's showing all of then.
5. We'll probably want to work on styling the menu bar since it's getting a little thick, but that can come later.
6. Seems 'Edit' is bugged.
7. There are some unresolved merge conflicts (ex: queryrunner, requirements)

2019-04-23 23:50 UTC, J8cob1 requested changes

2019-04-23 23:50 UTC, J8cob1 commented on .vscode/launch.json
> +{
This looks like an ide specific file. Should we have this here?

2019-04-23 23:50 UTC, J8cob1 commented on templates/form/response.html
> +>>>>>>> master
Unresolved

2019-04-23 23:50 UTC, J8cob1 commented on templates/form/review.html
>    {% extends "layout.html" %}
Unresolved merge conflict

2019-04-23 23:50 UTC, J8cob1 commented on app.py
> -                methods=['GET', 'POST'])
Do we need to nuke all of this code?

2019-04-23 23:50 UTC, J8cob1 commented on capstone360/__init__.py
> +# main file for server management
Do we need this file here right now? Didn't we remove this? I think we may need to move everything back into capstone360, but for now, no.

2019-04-23 23:50 UTC, J8cob1 commented on app.py
> +    return render_template('dashboard.html', lists=lists, sessions=sessions, team_names=team_names, member_names=member_names, form=form)
Can we put all of this into a MethodView class (like the ones in removeClass.py) and use an app.add_url_rule(...) command in app.py to add it to the app?

2019-04-25 02:41 UTC, closed without merging