working CAS for professors and students
capstoneteamb/capstone360 pull request #46
Opened 2019-05-04 08:18 UTC by longn5

CAS now checks if a professor is logging in.  If it is a professor then the professor dashboard is shown. 
 If the user is not a professor, it checks if they are in the student table.  If they are in the student table they are routed to the review.  If not then they are routed back to the homepage.

To test this, you need to add your CAT username into both the professor and student table.  Check to see if the professor dashboard shows up when logging in.  After this check, remove your username from the professor table.  Check login again, this time you will be routed to the student review form.

2019-05-04 09:57 UTC, pdx-cs-lbryan requested changes
* your CAT login name is currently in the DB, you may want to remove it

* submitting reviews currently doesn't work:
When logging in as a student, log in will take the user to /dashboard/, where they'll see the review
However, when they submit the review, because they are on /dashboard/, it is using prof_dashboard.py's post method. Thus, on submission, there's an exception that there is no 'session_id' in the form (line 61).

* form.py doesn't seem to have all instances of getting the student id changed to account for log in. A quick fix for now would be to change it in the 'get_id()' method and I can adjust the code later to be faster

2019-05-07 16:34 UTC, J8cob1 commented on gbmodel/model_sqlalchemy.py
> +    def get_professors(self, id):
So this block comment doesn't correct

2019-05-07 16:34 UTC, J8cob1 commented on gbmodel/model_sqlalchemy.py
> +        engine.execute("update capstone_session set midterm_start =:midterm_start, \
Weren't we trying to switch over to the ORM? Maybe we can fix this later (if we want this in now)?

2019-05-07 22:15 UTC, pdx-cs-lbryan requested changes
* After a student has submitted their review, they will see 'generate reports' on the page.

* If a user goes to /review/ directly (without logging in), an exception occurs:
get() missing 1 required positional argument: 'user_id'

2019-05-14 00:37 UTC, closed without merging