Encryption
capstoneteamb/capstone360 pull request #58
Opened 2019-05-10 18:39 UTC by cclevinger

2019-05-12 05:57 UTC, pdx-cs-lbryan requested changes
Logging into dashboard doesn't work
Reviews don't work
Edit: On further testing by manually adding an unencrypted name for log in purposes, I was able to log into the dashboard
from there:
clicking a student's name to view reports doesn't work
editing functionality results in bugs
switching sessions resulted in a bug
the report list doesn't work

Please remember to follow the guide in the coding styles document. You should only be requesting a review after testing out the application and ensuring that currently implemented features have not been broken by your update and that your new features are functional. Bugs will happen, but as many of them as possible should be removed prior to asking for review.

2019-06-02 08:57 UTC, pdx-cs-lbryan requested changes
key.txt should be removed
Some testing information would be very helpful

left some comments in the code.

doesn't look like professor info isn't encrypted, but I'm not sure what should be done there

it looks like review/reports information isn't being encrypted either

see slack comment

2019-06-02 08:57 UTC, pdx-cs-lbryan commented on gbmodel/model_sqlalchemy.py
> +key_file = open("../key.txt")
should have a try/except here

2019-06-02 08:57 UTC, pdx-cs-lbryan commented on gbmodel/model_sqlalchemy.py
> +def encrypt(p_text):
needs comments, error handling

2019-06-02 08:57 UTC, pdx-cs-lbryan commented on gbmodel/model_sqlalchemy.py
> +def decrypt(c_text):
needs comments/error handling

2019-06-02 08:57 UTC, pdx-cs-lbryan commented on gbmodel/model_sqlalchemy.py
> +            print(all_students)
not sure we want to be printing this

2019-06-02 08:59 UTC, pdx-cs-lbryan commented on gbmodel/model_sqlalchemy.py
> +key_file = open("../key.txt")
this line is also giving me an error with the current file structure of the repo

2019-06-06 03:29 UTC, pdx-cs-lbryan commented
A couple crashes I've found so far

When trying to remove students:
    st = students.query.filter(students.id == student.id,

    AttributeError: 'NoneType' object has no attribute 'id'

When trying to access the student dashboard:
    student_name = validate_student().name

    AttributeError: 'int' object has no attribute 'name'

2019-06-08 07:34 UTC, J8cob1 commented
Not needed anymore

2019-06-08 09:26 UTC, J8cob1 commented
Testing something...

2019-06-09 08:33 UTC, closed without merging