Changed model_sqlalchemy to ORM
capstoneteamb/capstone360 pull request #60
Opened 2019-05-12 06:36 UTC by anguye2

2019-05-12 07:09 UTC, pdx-cs-lbryan requested changes
db_session should be retained in the gb model files. The '#noqa' at the end of the involved lines will mean that this will pass the automatic linting checks, but on your own linter it may still show up as an error. This is a conflict between sqlalchemy and flake8 where the former requires it for other files, but because it's not actually called in the gbmodel files, flake8 thinks it's an error. As a result with the change, your branch is currently causing bugs to occur

2019-05-12 21:10 UTC, pdx-cs-lbryan commented
Is your task complete?
-removes raw sql statements from model

Is the branch caught up to master/are there merge conflicts still to be resolved?
ahead of master

Are old files unnecessarily introduced?
No

Is old code unnecessarily overwritten?
doesn't appear to be the case

Are new issues introduced to existing code? Do existing automated tests continue to work?
Log in: works
Dashboard: works
shows score range? yes
Edit:
-Can add students
-Can remove students
-can remove team
-can add team
-can remove all students from team
-changes reflected in DB
Review: can submit review
Prof Forms: Works

Report List:
**Bug encountered** (you might want to talk to Adam about this)
TypeError: 'Default MetaObject is not iterable'
seems to be coming from
report.py, line 161: for r in reports:
report.py. line 113: report = report + _make_student_report_pdf(s.id, session_id, is_final)
pdf = _make_printable_reports(session_id, team_id, is_final)

Set/Add Date: works
Automated Tests: pass

Uses 4 spaces where appropriate, not tabs?
yes

camelCase for class names, snake_case for variable and function names?
code is commented?
yes

Does the code handle edge cases? Are try/except statements used sufficiently?
No new issues added, but there's some statements in the model without try/except statements

Is there documentation on how to test your code somewhere?
no, but no new functionality

2019-05-12 21:33 UTC, necrobuffalo commented on gbmodel/model_sqlalchemy.py
>          return reports
I think this should probably be report?

2019-05-13 04:44 UTC, pdx-cs-lbryan approved these changes

2019-05-13 04:44 UTC, pdx-cs-lbryan commented
errors fixed

2019-05-13 04:44 UTC, merged